networkName: Your Network # Name of your network
networkWeb: yournetwork.org # Website of your network
gamePrefix: "DEFAULT" # PLEASE PUT IN SPEECH MARKS! Set as "DEFAULT" for classic HiveMC, else it will be your own.
mapBase: "maps" # Folder where the map base and maps folder is.

lockClassicKits: false # Do you want to lock classic kits such as Archer and Scout behind their permission?
lockUnlockableKits: true # Do you want to lock unlockable kits such as Mage and Sorcerer behind their permission?
showDeathBringerAt: 100000 # How many points must the top player surpass for the Death Bringer rank to show?

showDebugMessages: false # Show debug messages?

## Redis Configuration
redisHost: "localhost"
redisPort: 6379
redisPassword: "" # Leave this blank for no password

## SQL Configuration
sqlHost: "localhost"
sqlUsername: "username"
sqlPassword: "password"
sqlPort: 3306
