name: TheHerobrine-OG
main: uk.hotten.herobrine.HerobrinePluginOG
version: 1.3.1-1.1
api-version: 1.18
author: Gxorge
description: Remake of "The Herobrine!" v2 from HiveMC.
depend:
  - ProtocolLib
  - Multiverse-Core

commands:
  hbsetherobrine:
    description: Select a player to be Herobrine.
    permission: theherobrine.command.setherobrine
    usage: /<command> <player>

  hbforcestart:
    description: Force start the game.
    permission: theherobrine.command.forcestart
    usage: /<command> [time]

  hbdropshard:
    description: Drop the shard from the shard holder.
    permission: theherobrine.command.dropshard
    usage: /<command>

  hbpausetimer:
    description: Pause the start timer.
    permission: theherobrine.command.pausetimer
    usage: /<command>

  hbvote:
    description: Vote for a map.
    usage: /<command> <map number>
    aliases: [hbv]

  hbjoin:
    description: Join a lobby.
    usage: /<command> <lobby>

  hbcreatelobby:
    description: Create a lobby.
    permission: theherobrine.command.createlobby
    usage: /<command> <configuration id>

  hbdeletelobby:
    description: Delete a lobby.
    permission: theherobrine.command.deletelobby
    usage: /<command> <lobby id>

  hbspectate:
    description: Toggle spectator mode for a round.
    permission: theherobrine.command.spectate
    usage: /<command>

  hbreloadconfigs:
    description: Reload the lobby configuration files.
    permission: theherobrine.command.reloadconfigs
    usage: /<command>