name: TheHerobrine-OG
main: uk.hotten.herobrine.HerobrinePluginOG
version: PRE-1.0-master
api-version: 1.18
author: Gxorge
description: Remake of "The Herobrine!" v2 from HiveMC.
depend:
  - ProtocolLib