name: TheHerobrine
main: moe.gabriella.herobrine.HerobrinePlugin
author: Gabriella
version: 1.0.0
api-version: 1.16
description: Remake of "The Herobrine!" v2 from HiveMC.
depend: [ProtocolLib]
softdepend: [Vault]